# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDjangoDoc', '0002_auto_20160823_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MyPerson',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('TestDjangoDoc.personss',),
        ),
    ]
